version: '3'

services:
  snap:
    image: snapcore/snapcraft
    volumes:
      - build:/build
      - stage:/stage
      - ./snapcraft.yaml:/stage/snapcraft.yaml
      - ./snap:/stage/snap
      - .:/output
    working_dir: /stage
    depends_on:
      - piper
    command: 
      - "/bin/sh"
      - "-c"
      - "snapcraft clean && snapcraft && cp /stage/*.snap /output"
  piper:
    build: 
      context: ../..
      args:
        - VER=devel
    volumes:
      - build:/build
    command:
      - "/bin/sh"
      - "-c"
      - "/bin/cp /sshpiperd /build/sshpiperd && /build/sshpiperd version && sleep 1h"
volumes:
  build:
  stage:
